name: Inspetor de Qualidade (CI)

on: [push, pull_request] 
jobs:
  testar-api:
    runs-on:
    steps:
      - name: 1. Clonar o repositório
        uses: actions/checkout@v4 

      - name: 2. Instalar o interpretador (Node.js)
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
      
      - name: Instalar dependências do projeto
        run: npm install 
      
      - name:  Instalar npm
        run: npm install 

      - name: Instalar cors
        run: npm install cors
        
      - name: Instalar express
        run: npm install express

      - name: instalar teste
        run: npm install --save-dev jest 

      - name: Executar testes e garantir 90% de cobertura
        run: npm test