name: Validar Commits
on: [push]
jobs:
  integracao-continua:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Instalar o interpretador Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências do projeto
        run: npm install
      
      - name: Instalar npm
        run: npm install 

      - name: Instalar cors
        run: npm install cors
        
      - name: Instalar express
        run: npm install express

      - name: Para testes
        run: npm install --save-dev jest 